-- CreateTable
CREATE TABLE `Impactos` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `clas_seg` VARCHAR(10) NULL,
    `fechaHora` DATETIME NULL,
    `modulo_ur` VARCHAR(80) NULL,
    `pabellon` VARCHAR(80) NULL,
    `acontecimiento` VARCHAR(100) NULL,
    `observacion` TEXT NULL,
    `foco_igneo` VARCHAR(5) NULL,
    `reyerta` VARCHAR(5) NULL,
    `interv_requisa` VARCHAR(5) NULL,
    `expediente` VARCHAR(100) NULL,
    `establecimiento` VARCHAR(80) NULL,
    `email` VARCHAR(100) NULL,
    `internosinvolucrado` TEXT NULL,
    `imagenes` VARCHAR(191) NULL,
    `imagen` VARCHAR(255) NULL,
    `imagenDer` VARCHAR(255) NULL,
    `imagenIz` VARCHAR(255) NULL,
    `imagenDact` VARCHAR(255) NULL,
    `imagenSen1` VARCHAR(255) NULL,
    `imagenSen2` VARCHAR(255) NULL,
    `imagenSen3` VARCHAR(255) NULL,
    `imagenSen4` VARCHAR(255) NULL,
    `imagenSen5` VARCHAR(255) NULL,
    `imagenSen6` VARCHAR(255) NULL,
    `pdf1` VARCHAR(255) NULL,
    `pdf2` VARCHAR(255) NULL,
    `pdf3` VARCHAR(255) NULL,
    `pdf4` VARCHAR(255) NULL,
    `pdf5` VARCHAR(255) NULL,
    `pdf6` VARCHAR(255) NULL,
    `pdf7` VARCHAR(255) NULL,
    `pdf8` VARCHAR(255) NULL,
    `pdf9` VARCHAR(255) NULL,
    `pdf10` VARCHAR(255) NULL,
    `word1` VARCHAR(255) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Manifestaciones` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NULL,
    `clas_seg` VARCHAR(10) NULL,
    `establecimiento` VARCHAR(255) NULL,
    `modulo_ur` VARCHAR(255) NULL,
    `pabellon` VARCHAR(255) NULL,
    `sector` VARCHAR(255) NULL,
    `fechaHora` DATETIME NULL,
    `internosinvolucrado` TEXT NULL,
    `personalinvolucrado` LONGTEXT NULL,
    `foco_igneo` VARCHAR(5) NULL,
    `reyerta` VARCHAR(5) NULL,
    `interv_requisa` VARCHAR(5) NULL,
    `expediente` VARCHAR(255) NULL,
    `observacion` VARCHAR(191) NULL,
    `ims` VARCHAR(255) NULL,
    `rojos` VARCHAR(255) NULL,
    `email` VARCHAR(255) NULL,
    `imagen` VARCHAR(255) NULL,
    `imagenDer` VARCHAR(255) NULL,
    `imagenIz` VARCHAR(255) NULL,
    `imagenDact` VARCHAR(255) NULL,
    `imagenSen1` VARCHAR(255) NULL,
    `imagenSen2` VARCHAR(255) NULL,
    `imagenSen3` VARCHAR(255) NULL,
    `imagenSen4` VARCHAR(255) NULL,
    `imagenSen5` VARCHAR(255) NULL,
    `imagenSen6` VARCHAR(255) NULL,
    `pdf1` VARCHAR(255) NULL,
    `pdf2` VARCHAR(255) NULL,
    `pdf3` VARCHAR(255) NULL,
    `pdf4` VARCHAR(255) NULL,
    `pdf5` VARCHAR(255) NULL,
    `pdf6` VARCHAR(255) NULL,
    `pdf7` VARCHAR(255) NULL,
    `pdf8` VARCHAR(255) NULL,
    `pdf9` VARCHAR(255) NULL,
    `pdf10` VARCHAR(255) NULL,
    `word1` VARCHAR(255) NULL,
    `imagenes` VARCHAR(191) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Manifestaciones2` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `clas_seg` VARCHAR(10) NULL,
    `establecimiento` VARCHAR(100) NULL,
    `modulo_ur` VARCHAR(100) NULL,
    `sector` VARCHAR(150) NULL,
    `fechaHora` DATETIME NULL,
    `expediente` VARCHAR(100) NULL,
    `foco_igneo` VARCHAR(5) NULL,
    `reyerta` VARCHAR(5) NULL,
    `interv_requisa` VARCHAR(5) NULL,
    `observacion` VARCHAR(191) NULL,
    `personalinvolucrado` LONGTEXT NULL,
    `email` VARCHAR(255) NULL,
    `internosinvolucrado` TEXT NULL,
    `imagenes` VARCHAR(191) NULL,
    `imagen` VARCHAR(255) NULL,
    `imagenDer` VARCHAR(255) NULL,
    `imagenIz` VARCHAR(255) NULL,
    `imagenDact` VARCHAR(255) NULL,
    `imagenSen1` VARCHAR(255) NULL,
    `imagenSen2` VARCHAR(255) NULL,
    `imagenSen3` VARCHAR(255) NULL,
    `imagenSen4` VARCHAR(255) NULL,
    `imagenSen5` VARCHAR(255) NULL,
    `imagenSen6` VARCHAR(255) NULL,
    `pdf1` VARCHAR(255) NULL,
    `pdf2` VARCHAR(255) NULL,
    `pdf3` VARCHAR(255) NULL,
    `pdf4` VARCHAR(255) NULL,
    `pdf5` VARCHAR(255) NULL,
    `pdf6` VARCHAR(255) NULL,
    `pdf7` VARCHAR(255) NULL,
    `pdf8` VARCHAR(255) NULL,
    `pdf9` VARCHAR(255) NULL,
    `pdf10` VARCHAR(255) NULL,
    `word1` VARCHAR(255) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Agresiones` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `clas_seg` VARCHAR(10) NULL,
    `updatedAt` DATETIME(3) NOT NULL,
    `establecimiento` VARCHAR(60) NULL,
    `modulo_ur` VARCHAR(60) NULL,
    `pabellon` VARCHAR(60) NULL,
    `sector` VARCHAR(60) NULL,
    `personalinvolucrado` LONGTEXT NULL,
    `tipoAgresion` VARCHAR(500) NULL,
    `fechaHora` DATETIME NULL,
    `expediente` VARCHAR(150) NULL,
    `observacion` VARCHAR(191) NULL,
    `foco_igneo` VARCHAR(5) NULL,
    `reyerta` VARCHAR(5) NULL,
    `interv_requisa` VARCHAR(5) NULL,
    `ubicacionMap` LONGTEXT NULL,
    `email` VARCHAR(100) NULL,
    `internosinvolucrado` TEXT NULL,
    `imagenes` LONGTEXT NULL,
    `imagen` VARCHAR(255) NULL,
    `imagenDer` VARCHAR(255) NULL,
    `imagenIz` VARCHAR(255) NULL,
    `imagenDact` VARCHAR(255) NULL,
    `imagenSen1` VARCHAR(255) NULL,
    `imagenSen2` VARCHAR(255) NULL,
    `imagenSen3` VARCHAR(255) NULL,
    `imagenSen4` VARCHAR(255) NULL,
    `imagenSen5` VARCHAR(255) NULL,
    `imagenSen6` VARCHAR(255) NULL,
    `pdf1` VARCHAR(255) NULL,
    `pdf2` VARCHAR(255) NULL,
    `pdf3` VARCHAR(255) NULL,
    `pdf4` VARCHAR(255) NULL,
    `pdf5` VARCHAR(255) NULL,
    `pdf6` VARCHAR(255) NULL,
    `pdf7` VARCHAR(255) NULL,
    `pdf8` VARCHAR(255) NULL,
    `pdf9` VARCHAR(255) NULL,
    `pdf10` VARCHAR(255) NULL,
    `word1` VARCHAR(255) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Ingresos` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `lpu` VARCHAR(50) NULL,
    `identificadorUnico` VARCHAR(255) NULL,
    `createdAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `email` VARCHAR(255) NULL,
    `imagen` VARCHAR(255) NULL,
    `imagenDer` VARCHAR(255) NULL,
    `imagenIz` VARCHAR(255) NULL,
    `imagenDact` VARCHAR(255) NULL,
    `imagenSen1` VARCHAR(255) NULL,
    `imagenSen2` VARCHAR(255) NULL,
    `imagenSen3` VARCHAR(255) NULL,
    `imagenSen4` VARCHAR(255) NULL,
    `imagenSen5` VARCHAR(255) NULL,
    `imagenSen6` VARCHAR(255) NULL,
    `pdf1` VARCHAR(255) NULL,
    `pdf2` VARCHAR(255) NULL,
    `pdf3` VARCHAR(255) NULL,
    `pdf4` VARCHAR(255) NULL,
    `pdf5` VARCHAR(255) NULL,
    `pdf6` VARCHAR(255) NULL,
    `pdf7` VARCHAR(255) NULL,
    `pdf8` VARCHAR(255) NULL,
    `pdf9` VARCHAR(255) NULL,
    `pdf10` VARCHAR(255) NULL,
    `word1` VARCHAR(255) NULL,
    `imagenes` VARCHAR(191) NULL,
    `condicion` VARCHAR(20) NULL,
    `historialEgresos` JSON NULL,
    `unidadDeIngreso` VARCHAR(40) NULL,
    `fechaHoraIng` DATETIME NULL,
    `apellido` VARCHAR(150) NULL,
    `nombres` VARCHAR(255) NULL,
    `alias` VARCHAR(100) NULL,
    `tipoDoc` VARCHAR(12) NULL,
    `numeroDni` VARCHAR(50) NULL,
    `fechaNacimiento` DATETIME NULL,
    `edad_ing` VARCHAR(5) NULL,
    `nacionalidad` VARCHAR(40) NULL,
    `provincia` VARCHAR(100) NULL,
    `domicilios` LONGTEXT NULL,
    `numeroCausa` VARCHAR(255) NULL,
    `procedencia` VARCHAR(100) NULL,
    `orgCrim` VARCHAR(50) NULL,
    `cualorg` VARCHAR(100) NULL,
    `profesion` VARCHAR(100) NULL,
    `perfil` JSON NULL,
    `esAlerta` VARCHAR(3) NULL,
    `reingreso` LONGTEXT NULL,
    `establecimiento` VARCHAR(200) NULL,
    `modulo_ur` VARCHAR(60) NULL,
    `pabellon` VARCHAR(70) NULL,
    `celda` VARCHAR(70) NULL,
    `historial` LONGTEXT NULL,
    `titInfoPublic` LONGTEXT NULL,
    `resumen` LONGTEXT NULL,
    `observacion` VARCHAR(191) NULL,
    `link` LONGTEXT NULL,
    `patologias` JSON NULL,
    `tatuajes` JSON NULL,
    `cicatrices` JSON NULL,
    `ubicacionMap` LONGTEXT NULL,
    `electrodomesticos` JSON NULL,
    `electrodomesticosDetalles` LONGTEXT NULL,
    `juzgados` JSON NULL,
    `sitProc` VARCHAR(20) NULL,
    `lpuProv` VARCHAR(50) NULL,
    `subGrupo` VARCHAR(40) NULL,
    `sexo` VARCHAR(10) NULL,
    `sexualidad` VARCHAR(30) NULL,
    `temaInf` VARCHAR(191) NULL,
    `estadoCivil` VARCHAR(30) NULL,
    `internosinvolucrado` LONGTEXT NULL,
    `imagenesHistorial` JSON NULL,

    UNIQUE INDEX `Ingresos_identificadorUnico_key`(`identificadorUnico`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Preingresos` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `email` VARCHAR(255) NULL,
    `clasificacion` VARCHAR(25) NULL,
    `internosinvolucradoSimple` TEXT NULL,
    `fechaHoraIng` DATETIME NULL,
    `apellido` VARCHAR(150) NULL,
    `nombres` VARCHAR(255) NULL,
    `lpu` VARCHAR(50) NULL,
    `lpuProv` VARCHAR(50) NULL,
    `sitProc` VARCHAR(20) NULL,
    `alias` VARCHAR(100) NULL,
    `nacionalidad` VARCHAR(40) NULL,
    `provincia` VARCHAR(100) NULL,
    `fechaNacimiento` DATETIME NULL,
    `edad_ing` VARCHAR(5) NULL,
    `tipoDoc` VARCHAR(12) NULL,
    `numeroDni` VARCHAR(50) NULL,
    `domicilios` LONGTEXT NULL,
    `ubicacionMap` LONGTEXT NULL,
    `orgCrim` VARCHAR(50) NULL,
    `cualorg` VARCHAR(100) NULL,
    `procedencia` VARCHAR(100) NULL,
    `establecimiento` VARCHAR(200) NULL,
    `observacion` LONGTEXT NULL,
    `delitos` LONGTEXT NULL,
    `detalle_adicional` LONGTEXT NULL,
    `juzgados` LONGTEXT NULL,
    `org_judicial` VARCHAR(255) NULL,
    `numeroCausa` VARCHAR(50) NULL,
    `reingreso` LONGTEXT NULL,
    `reg_suv` VARCHAR(50) NULL,
    `reg_cir` VARCHAR(50) NULL,
    `titInfoPublic` LONGTEXT NULL,
    `resumen` LONGTEXT NULL,
    `link` LONGTEXT NULL,
    `cirDet` TEXT NULL,
    `t_r` VARCHAR(10) NULL,
    `electrodomesticos` JSON NULL,
    `electrodomesticosDetalles` LONGTEXT NULL,
    `internosinvolucrado` TEXT NULL,
    `imagen` VARCHAR(255) NULL,
    `imagenDer` VARCHAR(255) NULL,
    `imagenIz` VARCHAR(255) NULL,
    `imagenDact` VARCHAR(255) NULL,
    `imagenSen1` VARCHAR(255) NULL,
    `imagenSen2` VARCHAR(255) NULL,
    `imagenSen3` VARCHAR(255) NULL,
    `imagenSen4` VARCHAR(255) NULL,
    `imagenSen5` VARCHAR(255) NULL,
    `imagenSen6` VARCHAR(255) NULL,
    `pdf1` VARCHAR(255) NULL,
    `pdf2` VARCHAR(255) NULL,
    `pdf3` VARCHAR(255) NULL,
    `pdf4` VARCHAR(255) NULL,
    `pdf5` VARCHAR(255) NULL,
    `pdf6` VARCHAR(255) NULL,
    `pdf7` VARCHAR(255) NULL,
    `pdf8` VARCHAR(255) NULL,
    `pdf9` VARCHAR(255) NULL,
    `pdf10` VARCHAR(255) NULL,
    `word1` VARCHAR(255) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Prevenciones` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `clas_seg` VARCHAR(10) NULL,
    `fechaHora` DATETIME NULL,
    `reyerta` VARCHAR(5) NULL,
    `interv_requisa` VARCHAR(5) NULL,
    `foco_igneo` VARCHAR(5) NULL,
    `personalinvolucrado` TEXT NULL,
    `internosinvolucrado` TEXT NULL,
    `observacion` TEXT NULL,
    `expediente` VARCHAR(100) NULL,
    `email` VARCHAR(50) NULL,
    `establecimiento` VARCHAR(200) NULL,
    `modulo_ur` VARCHAR(50) NULL,
    `pabellon` VARCHAR(60) NULL,
    `sector` VARCHAR(100) NULL,
    `juzgados` JSON NULL,
    `imagenes` LONGTEXT NULL,
    `imagen` VARCHAR(255) NULL,
    `imagenDer` VARCHAR(255) NULL,
    `imagenIz` VARCHAR(255) NULL,
    `imagenDact` VARCHAR(255) NULL,
    `imagenSen1` VARCHAR(255) NULL,
    `imagenSen2` VARCHAR(255) NULL,
    `imagenSen3` VARCHAR(255) NULL,
    `imagenSen4` VARCHAR(255) NULL,
    `imagenSen5` VARCHAR(255) NULL,
    `imagenSen6` VARCHAR(255) NULL,
    `pdf1` VARCHAR(255) NULL,
    `pdf2` VARCHAR(255) NULL,
    `pdf3` VARCHAR(255) NULL,
    `pdf4` VARCHAR(255) NULL,
    `pdf5` VARCHAR(255) NULL,
    `pdf6` VARCHAR(255) NULL,
    `pdf7` VARCHAR(255) NULL,
    `pdf8` VARCHAR(255) NULL,
    `pdf9` VARCHAR(255) NULL,
    `pdf10` VARCHAR(255) NULL,
    `word1` VARCHAR(255) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Sumarios` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `clas_seg` VARCHAR(10) NULL,
    `evento` LONGTEXT NULL,
    `establecimiento` VARCHAR(200) NULL,
    `modulo_ur` VARCHAR(30) NULL,
    `fechaHora` DATETIME NULL,
    `expediente` VARCHAR(100) NULL,
    `personalinvolucrado` TEXT NULL,
    `internosinvolucrado` TEXT NULL,
    `observacion` LONGTEXT NULL,
    `archivos` LONGTEXT NULL,
    `email` VARCHAR(100) NULL,
    `imagenes` LONGTEXT NULL,
    `imagen` VARCHAR(255) NULL,
    `imagenDer` VARCHAR(255) NULL,
    `imagenIz` VARCHAR(255) NULL,
    `imagenDact` VARCHAR(255) NULL,
    `imagenSen1` VARCHAR(255) NULL,
    `imagenSen2` VARCHAR(255) NULL,
    `imagenSen3` VARCHAR(255) NULL,
    `imagenSen4` VARCHAR(255) NULL,
    `imagenSen5` VARCHAR(255) NULL,
    `imagenSen6` VARCHAR(255) NULL,
    `pdf1` VARCHAR(255) NULL,
    `pdf2` VARCHAR(255) NULL,
    `pdf3` VARCHAR(255) NULL,
    `pdf4` VARCHAR(255) NULL,
    `pdf5` VARCHAR(255) NULL,
    `pdf6` VARCHAR(255) NULL,
    `pdf7` VARCHAR(255) NULL,
    `pdf8` VARCHAR(255) NULL,
    `pdf9` VARCHAR(255) NULL,
    `pdf10` VARCHAR(255) NULL,
    `word1` VARCHAR(255) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Habeas` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `clas_seg` VARCHAR(10) NULL,
    `fechaHora` DATETIME NULL,
    `fechaHoraCierre` DATETIME NULL,
    `establecimiento` VARCHAR(200) NULL,
    `modulo_ur` VARCHAR(60) NULL,
    `pabellon` VARCHAR(60) NULL,
    `personalinvolucrado` TEXT NULL,
    `motivo` LONGTEXT NULL,
    `estado` VARCHAR(255) NULL,
    `expediente` VARCHAR(80) NULL,
    `observacion` LONGTEXT NULL,
    `email` VARCHAR(100) NULL,
    `internosinvolucrado` TEXT NULL,
    `imagenes` LONGTEXT NULL,
    `imagen` VARCHAR(255) NULL,
    `imagenDer` VARCHAR(255) NULL,
    `imagenIz` VARCHAR(255) NULL,
    `imagenDact` VARCHAR(255) NULL,
    `imagenSen1` VARCHAR(255) NULL,
    `imagenSen2` VARCHAR(255) NULL,
    `imagenSen3` VARCHAR(255) NULL,
    `imagenSen4` VARCHAR(255) NULL,
    `imagenSen5` VARCHAR(255) NULL,
    `imagenSen6` VARCHAR(255) NULL,
    `pdf1` VARCHAR(255) NULL,
    `pdf2` VARCHAR(255) NULL,
    `pdf3` VARCHAR(255) NULL,
    `pdf4` VARCHAR(255) NULL,
    `pdf5` VARCHAR(255) NULL,
    `pdf6` VARCHAR(255) NULL,
    `pdf7` VARCHAR(255) NULL,
    `pdf8` VARCHAR(255) NULL,
    `pdf9` VARCHAR(255) NULL,
    `pdf10` VARCHAR(255) NULL,
    `word1` VARCHAR(255) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Huelgas` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `clas_seg` VARCHAR(10) NULL,
    `establecimiento` VARCHAR(200) NULL,
    `modulo_ur` VARCHAR(80) NULL,
    `pabellon` VARCHAR(80) NULL,
    `internosinvolucrado` TEXT NULL,
    `fechaHora` DATETIME NULL,
    `fechaHoraCierre` DATETIME NULL,
    `expediente` VARCHAR(255) NULL,
    `motivo` VARCHAR(255) NULL,
    `estado` VARCHAR(255) NULL,
    `observacion` LONGTEXT NULL,
    `email` VARCHAR(100) NULL,
    `personalinvolucrado` LONGTEXT NULL,
    `imagenes` LONGTEXT NULL,
    `imagen` VARCHAR(255) NULL,
    `imagenDer` VARCHAR(255) NULL,
    `imagenIz` VARCHAR(255) NULL,
    `imagenDact` VARCHAR(255) NULL,
    `imagenSen1` VARCHAR(255) NULL,
    `imagenSen2` VARCHAR(255) NULL,
    `imagenSen3` VARCHAR(255) NULL,
    `imagenSen4` VARCHAR(255) NULL,
    `imagenSen5` VARCHAR(255) NULL,
    `imagenSen6` VARCHAR(255) NULL,
    `pdf1` VARCHAR(255) NULL,
    `pdf2` VARCHAR(255) NULL,
    `pdf3` VARCHAR(255) NULL,
    `pdf4` VARCHAR(255) NULL,
    `pdf5` VARCHAR(255) NULL,
    `pdf6` VARCHAR(255) NULL,
    `pdf7` VARCHAR(255) NULL,
    `pdf8` VARCHAR(255) NULL,
    `pdf9` VARCHAR(255) NULL,
    `pdf10` VARCHAR(255) NULL,
    `word1` VARCHAR(255) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Reqexts` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `organismo_requiriente` VARCHAR(255) NULL,
    `fechaHora` DATETIME NULL,
    `fechaHoraContestacion` DATETIME NULL,
    `nota` VARCHAR(255) NULL,
    `causa` VARCHAR(500) NULL,
    `estado` VARCHAR(255) NULL,
    `contestacion` LONGTEXT NULL,
    `observacion` LONGTEXT NULL,
    `internosinvolucradoSimple` TEXT NULL,
    `internosinvolucrado2` TEXT NULL,
    `email` VARCHAR(100) NULL,
    `imagenes` LONGTEXT NULL,
    `imagen` VARCHAR(255) NULL,
    `imagenDer` VARCHAR(255) NULL,
    `imagenIz` VARCHAR(255) NULL,
    `imagenDact` VARCHAR(255) NULL,
    `imagenSen1` VARCHAR(255) NULL,
    `imagenSen2` VARCHAR(255) NULL,
    `imagenSen3` VARCHAR(255) NULL,
    `imagenSen4` VARCHAR(255) NULL,
    `imagenSen5` VARCHAR(255) NULL,
    `imagenSen6` VARCHAR(255) NULL,
    `pdf1` VARCHAR(255) NULL,
    `pdf2` VARCHAR(255) NULL,
    `pdf3` VARCHAR(255) NULL,
    `pdf4` VARCHAR(255) NULL,
    `pdf5` VARCHAR(255) NULL,
    `pdf6` VARCHAR(255) NULL,
    `pdf7` VARCHAR(255) NULL,
    `pdf8` VARCHAR(255) NULL,
    `pdf9` VARCHAR(255) NULL,
    `pdf10` VARCHAR(255) NULL,
    `word1` VARCHAR(255) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Procedimientos` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NULL,
    `clas_seg` VARCHAR(10) NULL,
    `establecimiento` VARCHAR(255) NULL,
    `modulo_ur` VARCHAR(255) NULL,
    `pabellon` VARCHAR(255) NULL,
    `sector` VARCHAR(255) NULL,
    `fechaHora` DATETIME NULL,
    `expediente` VARCHAR(255) NULL,
    `tipo_procedimiento` VARCHAR(50) NULL,
    `por_orden_de` VARCHAR(300) NULL,
    `medidas` LONGTEXT NULL,
    `interv_requisa` VARCHAR(5) NULL,
    `observacion` VARCHAR(191) NULL,
    `personalinvolucrado` LONGTEXT NULL,
    `ims` VARCHAR(255) NULL,
    `rojos` VARCHAR(255) NULL,
    `email` VARCHAR(255) NULL,
    `internosinvolucrado` TEXT NULL,
    `imagenes` VARCHAR(191) NULL,
    `imagen` VARCHAR(255) NULL,
    `imagenDer` VARCHAR(255) NULL,
    `imagenIz` VARCHAR(255) NULL,
    `imagenDact` VARCHAR(255) NULL,
    `imagenSen1` VARCHAR(255) NULL,
    `imagenSen2` VARCHAR(255) NULL,
    `imagenSen3` VARCHAR(255) NULL,
    `imagenSen4` VARCHAR(255) NULL,
    `imagenSen5` VARCHAR(255) NULL,
    `imagenSen6` VARCHAR(255) NULL,
    `pdf1` VARCHAR(255) NULL,
    `pdf2` VARCHAR(255) NULL,
    `pdf3` VARCHAR(255) NULL,
    `pdf4` VARCHAR(255) NULL,
    `pdf5` VARCHAR(255) NULL,
    `pdf6` VARCHAR(255) NULL,
    `pdf7` VARCHAR(255) NULL,
    `pdf8` VARCHAR(255) NULL,
    `pdf9` VARCHAR(255) NULL,
    `pdf10` VARCHAR(255) NULL,
    `word1` VARCHAR(255) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Reqnos` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `email` VARCHAR(100) NULL,
    `requerido_por` VARCHAR(255) NULL,
    `observacion` LONGTEXT NULL,
    `datos_filiatorios` LONGTEXT NULL,
    `fechaHora` DATETIME NULL,
    `internosinvolucrado` TEXT NULL,
    `imagen` VARCHAR(255) NULL,
    `imagenDer` VARCHAR(255) NULL,
    `imagenIz` VARCHAR(255) NULL,
    `imagenDact` VARCHAR(255) NULL,
    `imagenSen1` VARCHAR(255) NULL,
    `imagenSen2` VARCHAR(255) NULL,
    `imagenSen3` VARCHAR(255) NULL,
    `imagenSen4` VARCHAR(255) NULL,
    `imagenSen5` VARCHAR(255) NULL,
    `imagenSen6` VARCHAR(255) NULL,
    `pdf1` VARCHAR(255) NULL,
    `pdf2` VARCHAR(255) NULL,
    `pdf3` VARCHAR(255) NULL,
    `pdf4` VARCHAR(255) NULL,
    `pdf5` VARCHAR(255) NULL,
    `pdf6` VARCHAR(255) NULL,
    `pdf7` VARCHAR(255) NULL,
    `pdf8` VARCHAR(255) NULL,
    `pdf9` VARCHAR(255) NULL,
    `pdf10` VARCHAR(255) NULL,
    `word1` VARCHAR(255) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Reqpositivos` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `imagen` VARCHAR(255) NULL,
    `fechaHora` DATETIME NULL,
    `establecimiento` VARCHAR(200) NULL,
    `internosinvolucrado` TEXT NULL,
    `fechaNacimiento` DATE NULL,
    `fechaEgreso` DATETIME NULL,
    `edad_ing` VARCHAR(5) NULL,
    `fechaHoraIng` DATETIME NULL,
    `alias` VARCHAR(100) NULL,
    `tipoDoc` VARCHAR(50) NULL,
    `numeroDni` VARCHAR(50) NULL,
    `nacionalidad` VARCHAR(120) NULL,
    `domicilios` VARCHAR(255) NULL,
    `ubicacionMap` VARCHAR(255) NULL,
    `sexo` VARCHAR(50) NULL,
    `registraantecedentespf` VARCHAR(10) NULL,
    `lpu` VARCHAR(255) NULL,
    `motivoEgreso` VARCHAR(150) NULL,
    `numeroCausa` VARCHAR(50) NULL,
    `prensa` LONGTEXT NULL,
    `observacion` LONGTEXT NULL,
    `juzgados` LONGTEXT NULL,
    `electrodomesticos` LONGTEXT NULL,
    `electrodomesticosDetalles` TEXT NULL,
    `sitProc` VARCHAR(100) NULL,
    `email` VARCHAR(100) NULL,
    `apellido` VARCHAR(255) NULL,
    `nombres` VARCHAR(255) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Riesgos` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `fechaHora` DATETIME NULL,
    `condicion` VARCHAR(20) NULL,
    `establecimiento` VARCHAR(200) NULL,
    `ubicacionMap` LONGTEXT NULL,
    `lpu` VARCHAR(150) NULL,
    `apellido` VARCHAR(150) NULL,
    `nombres` VARCHAR(150) NULL,
    `modulo_ur` VARCHAR(100) NULL,
    `pabellon` VARCHAR(100) NULL,
    `sitProc` VARCHAR(100) NULL,
    `condena` VARCHAR(255) NULL,
    `orgCrim` VARCHAR(255) NULL,
    `cualorg` VARCHAR(200) NULL,
    `rol` VARCHAR(200) NULL,
    `territorio` VARCHAR(255) NULL,
    `email` VARCHAR(100) NULL,
    `riesgo_de_fuga` VARCHAR(50) NULL,
    `riesgo_de_conf` VARCHAR(50) NULL,
    `restricciones` LONGTEXT NULL,
    `numeroCausa` VARCHAR(180) NULL,
    `observacion` LONGTEXT NULL,
    `infInd` LONGTEXT NULL,
    `allanamientos` LONGTEXT NULL,
    `secuestros` LONGTEXT NULL,
    `atentados` LONGTEXT NULL,
    `electrodomesticos` LONGTEXT NULL,
    `fzaSeg` LONGTEXT NULL,
    `electrodomesticosDetalles` LONGTEXT NULL,
    `sociedad` LONGTEXT NULL,
    `im` LONGTEXT NULL,
    `sexo` VARCHAR(10) NULL,
    `enemistad` LONGTEXT NULL,
    `reeval` VARCHAR(5) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,
    `internosinvolucrado` TEXT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Extramuros` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `clas_seg` VARCHAR(10) NULL,
    `fechaHora` DATETIME NULL,
    `fechaHoraReintegro` DATETIME NULL,
    `internacion` VARCHAR(50) NULL,
    `porOrden` VARCHAR(50) NULL,
    `observacion` LONGTEXT NULL,
    `establecimiento` VARCHAR(200) NULL,
    `sector_internacion` VARCHAR(255) NULL,
    `piso` VARCHAR(255) NULL,
    `habitacion` VARCHAR(255) NULL,
    `cama` VARCHAR(255) NULL,
    `motivo_reintegro` VARCHAR(255) NULL,
    `modulo_ur` VARCHAR(255) NULL,
    `pabellon` VARCHAR(255) NULL,
    `hospital` VARCHAR(255) NULL,
    `motivo` VARCHAR(255) NULL,
    `email` VARCHAR(255) NULL,
    `expediente` VARCHAR(255) NULL,
    `internosinvolucrado` TEXT NULL,
    `personalinvolucrado` TEXT NULL,
    `imagenes` LONGTEXT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `imagen` VARCHAR(255) NULL,
    `imagenDer` VARCHAR(255) NULL,
    `imagenIz` VARCHAR(255) NULL,
    `imagenDact` VARCHAR(255) NULL,
    `imagenSen1` VARCHAR(255) NULL,
    `imagenSen2` VARCHAR(255) NULL,
    `imagenSen3` VARCHAR(255) NULL,
    `imagenSen4` VARCHAR(255) NULL,
    `imagenSen5` VARCHAR(255) NULL,
    `imagenSen6` VARCHAR(255) NULL,
    `pdf1` VARCHAR(255) NULL,
    `pdf2` VARCHAR(255) NULL,
    `pdf3` VARCHAR(255) NULL,
    `pdf4` VARCHAR(255) NULL,
    `pdf5` VARCHAR(255) NULL,
    `pdf6` VARCHAR(255) NULL,
    `pdf7` VARCHAR(255) NULL,
    `pdf8` VARCHAR(255) NULL,
    `pdf9` VARCHAR(255) NULL,
    `pdf10` VARCHAR(255) NULL,
    `word1` VARCHAR(255) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Elementos` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `clas_seg` VARCHAR(10) NULL,
    `createdAt` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `prevencion` VARCHAR(255) NULL,
    `establecimiento` VARCHAR(200) NULL,
    `modulo_ur` VARCHAR(80) NULL,
    `pabellon` VARCHAR(80) NULL,
    `fechaHora` DATETIME NOT NULL,
    `expediente` VARCHAR(255) NULL,
    `observacion` LONGTEXT NULL,
    `medidas` TEXT NULL,
    `dentroDePabellon` VARCHAR(255) NULL,
    `imagenes` LONGTEXT NULL,
    `estupefacientes` LONGTEXT NULL,
    `internosinvolucrado` TEXT NULL,
    `personalinvolucrado` TEXT NULL,
    `email` VARCHAR(100) NULL,
    `armas` LONGTEXT NULL,
    `electronicos` LONGTEXT NULL,
    `componentes` LONGTEXT NULL,
    `imagen` VARCHAR(255) NULL,
    `imagenDer` VARCHAR(255) NULL,
    `imagenIz` VARCHAR(255) NULL,
    `imagenDact` VARCHAR(255) NULL,
    `imagenSen1` VARCHAR(255) NULL,
    `imagenSen2` VARCHAR(255) NULL,
    `imagenSen3` VARCHAR(255) NULL,
    `imagenSen4` VARCHAR(255) NULL,
    `imagenSen5` VARCHAR(255) NULL,
    `imagenSen6` VARCHAR(255) NULL,
    `pdf1` VARCHAR(255) NULL,
    `pdf2` VARCHAR(255) NULL,
    `pdf3` VARCHAR(255) NULL,
    `pdf4` VARCHAR(255) NULL,
    `pdf5` VARCHAR(255) NULL,
    `pdf6` VARCHAR(255) NULL,
    `pdf7` VARCHAR(255) NULL,
    `pdf8` VARCHAR(255) NULL,
    `pdf9` VARCHAR(255) NULL,
    `pdf10` VARCHAR(255) NULL,
    `word1` VARCHAR(255) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Atentados` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NULL,
    `clas_seg` VARCHAR(10) NULL,
    `personalinvolucrado` TEXT NULL,
    `ims` LONGTEXT NULL,
    `fechaHora` DATETIME NULL,
    `internosinvolucrado` TEXT NULL,
    `establecimiento` VARCHAR(200) NULL,
    `modulo_ur` VARCHAR(80) NULL,
    `pabellon` VARCHAR(80) NULL,
    `acontecimiento` VARCHAR(100) NULL,
    `jurisdiccion` LONGTEXT NULL,
    `juzgados` JSON NULL,
    `prevencioSiNo` VARCHAR(5) NULL,
    `fechaVenc` VARCHAR(5) NULL,
    `ordenCapDip` VARCHAR(5) NULL,
    `expediente` VARCHAR(100) NULL,
    `observacion` TEXT NULL,
    `otrosDatos` TEXT NULL,
    `fechaHoraVencTime` DATETIME NULL,
    `fechaHoraUlOrCap` DATETIME NULL,
    `email` VARCHAR(255) NULL,
    `imagen` VARCHAR(255) NULL,
    `imagenDer` VARCHAR(255) NULL,
    `imagenIz` VARCHAR(255) NULL,
    `imagenDact` VARCHAR(255) NULL,
    `imagenSen1` VARCHAR(255) NULL,
    `imagenSen2` VARCHAR(255) NULL,
    `imagenSen3` VARCHAR(255) NULL,
    `imagenSen4` VARCHAR(255) NULL,
    `imagenSen5` VARCHAR(255) NULL,
    `imagenSen6` VARCHAR(255) NULL,
    `pdf1` VARCHAR(255) NULL,
    `pdf2` VARCHAR(255) NULL,
    `pdf3` VARCHAR(255) NULL,
    `pdf4` VARCHAR(255) NULL,
    `pdf5` VARCHAR(255) NULL,
    `pdf6` VARCHAR(255) NULL,
    `pdf7` VARCHAR(255) NULL,
    `pdf8` VARCHAR(255) NULL,
    `pdf9` VARCHAR(255) NULL,
    `pdf10` VARCHAR(255) NULL,
    `word1` VARCHAR(255) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Egresos` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NULL,
    `clas_seg` VARCHAR(10) NULL,
    `personalinvolucrado` TEXT NULL,
    `ims` LONGTEXT NULL,
    `fechaHora` DATETIME NULL,
    `internosinvolucrado` TEXT NULL,
    `establecimiento` VARCHAR(200) NULL,
    `modulo_ur` VARCHAR(80) NULL,
    `pabellon` VARCHAR(80) NULL,
    `jurisdiccion` LONGTEXT NULL,
    `juzgados` JSON NULL,
    `prevencioSiNo` VARCHAR(5) NULL,
    `fechaVenc` VARCHAR(5) NULL,
    `ordenCapDip` VARCHAR(5) NULL,
    `reintFueraTerm` VARCHAR(5) NULL,
    `revArrDom` VARCHAR(5) NULL,
    `revLibCond` VARCHAR(5) NULL,
    `revlibAsis` VARCHAR(5) NULL,
    `reingPorRecap` VARCHAR(5) NULL,
    `detalle` TEXT NULL,
    `fechaHoraReintFueTerm` DATETIME NULL,
    `fechaHoraReingPorRecap` DATETIME NULL,
    `expediente` VARCHAR(100) NULL,
    `observacion` TEXT NULL,
    `otrosDatos` TEXT NULL,
    `fechaHoraVencTime` DATETIME NULL,
    `fechaHoraUlOrCap` DATETIME NULL,
    `plazo` VARCHAR(10) NULL,
    `tipoDeSalida` VARCHAR(100) NULL,
    `modalidad` VARCHAR(100) NULL,
    `noReintSalTra` VARCHAR(5) NULL,
    `email` VARCHAR(255) NULL,
    `imagen` VARCHAR(255) NULL,
    `imagenDer` VARCHAR(255) NULL,
    `imagenIz` VARCHAR(255) NULL,
    `imagenDact` VARCHAR(255) NULL,
    `imagenSen1` VARCHAR(255) NULL,
    `imagenSen2` VARCHAR(255) NULL,
    `imagenSen3` VARCHAR(255) NULL,
    `imagenSen4` VARCHAR(255) NULL,
    `imagenSen5` VARCHAR(255) NULL,
    `imagenSen6` VARCHAR(255) NULL,
    `pdf1` VARCHAR(255) NULL,
    `pdf2` VARCHAR(255) NULL,
    `pdf3` VARCHAR(255) NULL,
    `pdf4` VARCHAR(255) NULL,
    `pdf5` VARCHAR(255) NULL,
    `pdf6` VARCHAR(255) NULL,
    `pdf7` VARCHAR(255) NULL,
    `pdf8` VARCHAR(255) NULL,
    `pdf9` VARCHAR(255) NULL,
    `pdf10` VARCHAR(255) NULL,
    `word1` VARCHAR(255) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Temas` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `fechaHora` DATETIME NULL,
    `observacion` LONGTEXT NULL,
    `email` VARCHAR(100) NULL,
    `internosinvolucrado` TEXT NULL,
    `establecimiento` VARCHAR(200) NULL,
    `modulo_ur` VARCHAR(80) NULL,
    `pabellon` VARCHAR(90) NULL,
    `imagenes` LONGTEXT NULL,
    `imagen` VARCHAR(255) NULL,
    `imagenDer` VARCHAR(255) NULL,
    `imagenIz` VARCHAR(255) NULL,
    `imagenDact` VARCHAR(255) NULL,
    `imagenSen1` VARCHAR(255) NULL,
    `imagenSen2` VARCHAR(255) NULL,
    `imagenSen3` VARCHAR(255) NULL,
    `imagenSen4` VARCHAR(255) NULL,
    `imagenSen5` VARCHAR(255) NULL,
    `imagenSen6` VARCHAR(255) NULL,
    `pdf1` VARCHAR(255) NULL,
    `pdf2` VARCHAR(255) NULL,
    `pdf3` VARCHAR(255) NULL,
    `pdf4` VARCHAR(255) NULL,
    `pdf5` VARCHAR(255) NULL,
    `pdf6` VARCHAR(255) NULL,
    `pdf7` VARCHAR(255) NULL,
    `pdf8` VARCHAR(255) NULL,
    `pdf9` VARCHAR(255) NULL,
    `pdf10` VARCHAR(255) NULL,
    `word1` VARCHAR(255) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Traslados` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `clas_seg` VARCHAR(10) NULL,
    `fechaHora` DATETIME NULL,
    `fechaTraslado` DATETIME NULL,
    `establecimiento` VARCHAR(200) NULL,
    `establecimiento2` VARCHAR(200) NULL,
    `comunicacion` VARCHAR(100) NULL,
    `disposicion` VARCHAR(255) NULL,
    `disposicion2` VARCHAR(255) NULL,
    `motivo` TEXT NULL,
    `internosinvolucrado` TEXT NULL,
    `email` VARCHAR(100) NULL,
    `imagenes` VARCHAR(191) NULL,
    `imagen` VARCHAR(255) NULL,
    `imagenDer` VARCHAR(255) NULL,
    `imagenIz` VARCHAR(255) NULL,
    `imagenDact` VARCHAR(255) NULL,
    `imagenSen1` VARCHAR(255) NULL,
    `imagenSen2` VARCHAR(255) NULL,
    `imagenSen3` VARCHAR(255) NULL,
    `imagenSen4` VARCHAR(255) NULL,
    `imagenSen5` VARCHAR(255) NULL,
    `imagenSen6` VARCHAR(255) NULL,
    `pdf1` VARCHAR(255) NULL,
    `pdf2` VARCHAR(255) NULL,
    `pdf3` VARCHAR(255) NULL,
    `pdf4` VARCHAR(255) NULL,
    `pdf5` VARCHAR(255) NULL,
    `pdf6` VARCHAR(255) NULL,
    `pdf7` VARCHAR(255) NULL,
    `pdf8` VARCHAR(255) NULL,
    `pdf9` VARCHAR(255) NULL,
    `pdf10` VARCHAR(255) NULL,
    `word1` VARCHAR(255) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Users` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `email` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `privilege` VARCHAR(191) NULL,
    `internosinvolucrado` TEXT NULL,

    UNIQUE INDEX `Users_email_key`(`email`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
