//frontend\src\app\utils\eventFields.tsx
export const camposPorEvento: { [key: string]: string[] } = {
  temas: [
    "fechaHora",
    "patente",
    "marca",
    "modelo",
    "anio",
    "color",
    "tipoPintura",
    "tipoVehic",
    "motor",
    "chasis",
    "combustion",
    "vin",
    "observacion",
    "email",
    "createdAt",
    "updatedAt",
  ],
  presupuestos: [
    "patente",
    "monto",
    "estado",
    "observaciones",
    "createdAt",
    "updatedAt",
  ],
  ingresos: [
    "apellido",
    "nombres",
    "numeroDni",
    "numeroCuit",
    "telefono",
    "emailCliente",
    "domicilios",
    "provincia",
    "iva",
    "pyme",
    "observacion",
    "createdAt",
    "updatedAt",
  ],
};
